name: publish-next

on:
    pull_request:
        types: [opened, synchronize]
jobs:
  next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: |
          echo "@vacasaoss:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm ci
      - run: npm run ci
      - uses: adobe/update-prerelease-npm-version@v1.1.0
        with:
          skip-dependencies-to-update: true
          package-json-path: 'ts-force/package.json'
      - run: echo ${{ steps.pre-release-version.outputs.pre-release-version }} 
      - uses: adobe/update-prerelease-npm-version@v1.1.0
        with:
          skip-dependencies-to-update: true
          package-json-path: 'ts-force-gen/package.json'
      - run: echo ${{ steps.pre-release-version.outputs.pre-release-version }} 
      - run: cd $GITHUB_WORKSPACE/ts-force && cp ../.npmrc . && npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: cd $GITHUB_WORKSPACE/ts-force-gen && cp ../.npmrc . && npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}